server:
  port: 8080
spring:
  application:
    attendance
  datasource:
    url: jdbc:mysql://localhost:3306/attendance
    username: root
    password: 33333333
    driver-class-name: com.mysql.cj.jdbc.Driver

mvc:
  pathmatch:
    matching-strategy:ant_path_matcher

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#mybatis:
# mapper-location: classpath*:mybatis/mapper/*Mappers.xml